### PR TITLE
[Imp] Added slot to customize node markup

### PR DESCRIPTION
**Pull request by Astatroth**
Added slot support to make it easier to customize the node markup (add buttons or whatever).

### CODE REVIEW

**Comment by shuiRong** [comment]
That's awesome! Thanks for your contribution.

**Comment by shuiRong** [comment]
But it seems has a little problem. the parent element couldn't use the child component's variable.
I will fix it.

**Comment by Astatroth** [comment]
> But it seems has a little problem. the parent element couldn't use the child component's variable.
> I will fix it.

I missed that )

**Comment by Astatroth** [comment]
Also you may want to add some info regarding using slots to the readme )

**Comment by shuiRong** [comment]
🎉 done. (including README)

**Comment by Astatroth** [comment]
Great! )

**Pull request merged**
